import Navbar from "@/components/Navbar";
import "./globals.css";
import { Nunito } from "next/font/google";
import Footer from "@/components/Footer";

const nunito = Nunito({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Aashutosh Singh - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-gradient-to-tr from-sky-200 from-40% via-cyan-500 to-blue-200 to-70% ${nunito.className}`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
